'''

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.


'''


def findTheDifference(s: str, t: str) -> str:
    num1 = 0
    num2 = 0
    for i in t:
        x = ord(i)
        num1 = num1 + x

    for i in s:
        x = ord(i)
        num2 = num2 + x
    
    return(chr(num1-num2))


s = "abcd"
t = "abcde"
print(findTheDifference(s,t))